name: THEJB.AI
author: JB
description: "JB의 AI 논문 구현 및 리뷰"

url: https://thejb.ai

img_baseurl: "https://img.thejb.ai"

permalink: /:title/

kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: ''
    # line_numbers: true
    default_lang: python
    guess_lang: true

remote_theme: "the-jb/thejb.ai-theme"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

sass:
  style: :compressed

gems:

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

giscus:
  src: "https://giscus.app/client.js"
  data_repo: "the-jb/thejb.ai"
  data_repo_id: "MDEwOlJlcG9zaXRvcnkyMjY3NTQ5MDk="
  data_category: "Posts"
  data_category_id: "DIC_kwDODYQBXc4B_CDg"
  data_mapping: "og:title"
  data_reactions_enabled: "0"
  data_emit_metadata: "0"
  data_theme: "light"
  crossorigin: "anonymous"
